name: Scan code with Snyk

on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authenticate with Snyk
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Run Snyk to check for vulnerabilities in all .sln files recursively
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --file=**/*.sln --sarif-file-output=snyk.sarif --all-projects

      # Upload Snyk results to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
