name: Scan code with Snyk

on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authenticate with Snyk
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Find all .sln files and run snyk test on each
      - name: Run Snyk to check for vulnerabilities
        run: |
          # Find all .sln files and run snyk test for each
          for sln_file in $(find . -name "*.sln"); do
            snyk test --file=$sln_file --sarif-file-output=snyk.sarif
          done

      # Upload Snyk results to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
